### ISSUE TITLE
Invalid table names prefix

### ISSUE THREAD

**Issue by mudrd8mz** [HFTSoftwareProject/moodle-assignsubmission_mojec#6]
The plugin creates tables mojec_testresult, mojec_testfailure, mojec_compilationerror which do not have expected prefix. All this plugin's tables should have the name like `assignsubmission_mojec_*`

**Comment by mudrd8mz** [comment]
Just wondering if the reason is that you started to hit the table name length limit?

**Comment by lueckemeyer** [comment]
Dear mudrd8mz,
your last guess is right: with the 16 character "assignsubmission_"-prefix, a meaningful table name is just not possible. Thus, the issue is rejected until the table name length limit in moodle (or Oracle, which seems to be the critical database) increases.
